CREATE TABLE `biblioteca`.`EMPLEADO`(
	`RFC` VARCHAR(13) NOT NULL,
	`CONTRASEÑA` VARCHAR(16) NOT NULL,
	`NOMBRE` VARCHAR(100) NOT NULL,
	`INGRESO`  TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP NOT NULL,
	`TELEFONO` BIGINT(10) NOT NULL,
	`SALARIO` FLOAT(30) NOT NULL,
	`CARGO` VARCHAR(13) NOT NULL,
	`DOMICILIO` VARCHAR(100) NOT NULL,
    `ESTADO` BOOLEAN DEFAULT TRUE,
	`CORREO` VARCHAR(100) NOT NULL,
	PRIMARY KEY(`RFC`)
) ENGINE = InnoDB;

CREATE TABLE `biblioteca`.`USUARIO`(
	`IDUSUARIO` INT NOT NULL AUTO_INCREMENT,
	`NOMBRE` VARCHAR(100) NOT NULL,
	`CONTRASEÑA` VARCHAR(16) NOT NULL,
	`TELEFONO` BIGINT(10) NOT NULL,
    `ESTADO` BOOLEAN DEFAULT TRUE,
	`TIPO` VARCHAR(13) NOT NULL,  
	PRIMARY KEY(`IDUSUARIO`)
) ENGINE = InnoDB;

CREATE TABLE `biblioteca`.`VISITAS`(
	`IDVISITA` INT NOT NULL AUTO_INCREMENT,
	`IDUSUARIO` INT NOT NULL,
	`VISITA`  TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (`IDUSUARIO`) REFERENCES USUARIO(IDUSUARIO),
	PRIMARY KEY(`IDVISITA`)
) ENGINE = InnoDB;

CREATE TABLE `biblioteca`.`TITULO`(
	`IDTITULO` VARCHAR(13) NOT NULL,
	`NOMBRE` VARCHAR(100) NOT NULL,
	`AUTOR` VARCHAR(100) NOT NULL,
	`EDICION` INT NOT NULL,
	`SCDD` BIGINT(10) NOT NULL,
	`EDITORIAL` VARCHAR(100) NOT NULL,
	PRIMARY KEY(`IDTITULO`)
) ENGINE = InnoDB;

CREATE TABLE `biblioteca`.`LIBRO`(
	`IDLIBRO` INT NOT NULL AUTO_INCREMENT,
	`IDTITULO`  VARCHAR(13) NOT NULL,
	`EJEMPLAR` INT NOT NULL,
	`COSTO` FLOAT NOT NULL,
	`DAÑOS` VARCHAR(9) NOT NULL,  
    `ESTADO` BOOLEAN DEFAULT FALSE,

    FOREIGN KEY (`IDTITULO`) REFERENCES TITULO(IDTITULO),
	PRIMARY KEY(`IDLIBRO`)
) ENGINE = InnoDB;

CREATE TABLE `biblioteca`.`MEMBRESIA`(
	`IDMEMBRESIA` INT NOT NULL AUTO_INCREMENT,
	`IDUSUARIO` INT NOT NULL,
	`NACIMIENTO` DATE NOT NULL,
	`DOMICILIO` VARCHAR(100) NOT NULL,
	`EXPIRACION` DATE NOT NULL,
	`CORREO` VARCHAR(100) NOT NULL,
	`EXPEDICION`  TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `ESTADO` BOOLEAN DEFAULT FALSE,

    FOREIGN KEY (`IDUSUARIO`) REFERENCES USUARIO(IDUSUARIO),
	PRIMARY KEY(`IDMEMBRESIA`)
) ENGINE = InnoDB;

CREATE TABLE `biblioteca`.`PRESTAMO`(
	`IDPRESTAMO` INT NOT NULL AUTO_INCREMENT,
	`IDMEMBRESIA` INT NOT NULL,
	`SOLICITUD`  TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	`ENTREGA` DATE NOT NULL,

    FOREIGN KEY (`IDMEMBRESIA`) REFERENCES MEMBRESIA(IDMEMBRESIA),
	PRIMARY KEY(`IDPRESTAMO`)

) ENGINE = InnoDB;

CREATE TABLE `biblioteca`.`DETALLEPRESTAMO`(
	`IDDETALEPRESTAMO` INT NOT NULL AUTO_INCREMENT,
	`IDPRESTAMO` INT NOT NULL,
	`IDLIBRO` INT NOT NULL,

    FOREIGN KEY (`IDPRESTAMO`) REFERENCES PRESTAMO(IDPRESTAMO),
    FOREIGN KEY (`IDLIBRO`) REFERENCES LIBRO(IDLIBRO),
	PRIMARY KEY(`IDDETALEPRESTAMO`)
    
) ENGINE = InnoDB;

CREATE TABLE `biblioteca`.`COBRO`(
	`IDCOBRO` INT NOT NULL AUTO_INCREMENT,
	`IDPRESTAMO` INT NOT NULL,
    `ESTADO` BOOLEAN DEFAULT FALSE,
	`ENTREGA` DATE NOT NULL,
	`ENTREGAREAL` DATE NOT NULL,

    FOREIGN KEY (`IDPRESTAMO`) REFERENCES PRESTAMO(IDPRESTAMO),
	PRIMARY KEY(`IDCOBRO`)
    
) ENGINE = InnoDB;

CREATE TABLE `biblioteca`.`DETALLECOBRO`(
	`IDDETALLECOBRO` INT NOT NULL AUTO_INCREMENT,
	`IDCOBRO` INT NOT NULL,
	`IDLIBRO` INT NOT NULL,
	`DAMAGE` VARCHAR(9) NOT NULL,
	`MONTO` FLOAT NOT NULL,
    `ESTADO` BOOLEAN,

    FOREIGN KEY (`IDCOBRO`) REFERENCES COBRO(IDCOBRO),
    FOREIGN KEY (`IDLIBRO`) REFERENCES LIBRO(IDLIBRO),
	PRIMARY KEY(`IDDETALLECOBRO`)
    
) ENGINE = InnoDB;